# Generated by Django 2.1.7 on 2019-03-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_pinjam',
            fields=[
                ('id_detail_pinjam', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('id_inventaris', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('kondisi', models.CharField(choices=[('BARU', 'BARU'), ('BEKAS', 'BEKAS')], max_length=5)),
                ('keterangan', models.TextField()),
                ('jumlah', models.IntegerField()),
                ('tanggal_register', models.DateField()),
                ('kode_inventaris', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id_jenis', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('nama_jenis', models.CharField(max_length=30)),
                ('kode_jenis', models.CharField(max_length=10)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('nama_pegawai', models.CharField(max_length=30)),
                ('nip', models.CharField(max_length=10)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('status_peminjaman', models.CharField(choices=[('Dikembalikan', 'Dikembalikan'), ('Belum_Dikembalikan', 'Belum_Dikembalikan')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('nama_petugas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id_ruang', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('nama_ruang', models.CharField(max_length=30)),
                ('kode_ruang', models.CharField(max_length=10)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('kode_stock', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('nama_barang', models.CharField(max_length=5)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='inventaris',
            name='id_jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Jenis'),
        ),
        migrations.AddField(
            model_name='inventaris',
            name='id_petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Petugas'),
        ),
        migrations.AddField(
            model_name='detail_pinjam',
            name='id_inventaris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Inventaris'),
        ),
    ]
