# Generated by Django 2.1.7 on 2019-04-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petugas',
            name='password',
        ),
        migrations.RemoveField(
            model_name='petugas',
            name='username',
        ),
    ]
