# Generated by Django 2.1.7 on 2019-04-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_auto_20190407_0613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
